#!/usr/bin/env bash

sudo -v

fancy_echo() {
  printf "\n%b\n" "$1"
}

less_fancy_echo() {
  printf "%b\n" "$1"
}

fancy_echo "Setting up ssh key..."
  if [ ! -d ~/.ssh ]; then
    ssh-keygen -t rsa -b 4096 -C "paris.yee@gmail.com"
    eval "$(ssh-agent -s)"
    cat <<EOT>> ~/.ssh/config
Host *
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_rsa
EOT
    ssh-add -K ~/.ssh/id_rsa
    pbcopy < ~/.ssh/id_rsa.pub

    read -p "SSH key copied to clipboard. Add to Github account the press [Enter] to continue."
  else
    less_fancy_echo ".ssh directory already exists. Skipping ..."
  fi

if [[ ! -d "$HOME/.bin/" ]]; then
  mkdir "$HOME/.bin"
fi

if ! type brew &>/dev/null; then
  fancy_echo "Installing Homebrew ..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    export PATH="/usr/local/bin:$PATH"
else
  fancy_echo "Homebrew already installed. Skipping ..."
fi

fancy_echo "Updating Homebrew formulas ..."
brew update

brew_install() {
  if brew list -1 | grep -q "^$1"; then
    less_fancy_echo "... skipping $1, already installed"
  else
    brew install $1
  fi

  true
}

brew_tap() {
  if brew tap -1 | grep -q "^$1"; then
    less_fancy_echo "... skipping $1, already tapped"
  else
    brew tap $1
  fi

  true
}

fancy_echo "Installing Git ..."
  brew_install git

fancy_echo "Installing The Silver Searcher (better than ack or grep) to search the contents of files ..."
  brew_install the_silver_searcher

fancy_echo "Installing vim from Homebrew to get the latest version ..."
  brew_install "vim --override-system-vi"

fancy_echo "Installing ctags, to index files for vim tab completion of methods, classes, variables ..."
  brew_install ctags

fancy_echo "Installing tmux, to save project state and switch between projects ..."
  brew_install tmux

fancy_echo "Installing Bash Completion, for better bash completion ..."
  brew_install bash-completion

fancy_echo "Installing fd, for finding things more easily ..."
  brew_install fd

fancy_echo "Installing rcm, for dotfile management ..."
  brew_tap thoughtbot/formulae
  brew_install rcm

fancy_echo "Installing Brew Cask, to install OSX binaries ..."

brew_cask_list() {
  brew cask list 2> /dev/null || true
}

# run this once, the command is slow
CASKS=$(brew_cask_list)

is_brew_cask_installed() {
  echo ${CASKS} | grep -q "\b$1"
}

brew_cask_install() {
  if is_brew_cask_installed $1; then
    less_fancy_echo "... skipping cask $1, already installed"
  else
    brew cask install $1 2> /dev/null || true
  fi

  true
}

fancy_echo "Installing Google Chrome ..."
  brew_cask_install google-chrome

fancy_echo "Installing 1Password ..."
  brew_cask_install 1password

fancy_echo "Installing Firefox ..."
  brew_cask_install firefox

fancy_echo "Installing TextMate ..."
  brew_cask_install textmate

fancy_echo "Installing iTerm2 ..."
  brew_cask_install iterm2

fancy_echo "Installing MacVim ..."
  brew_cask_install macvim

fancy_echo "Installing Typora ..."
  brew_cask_install typora
  
fancy_echo "Installing Dropbox..."
  brew_cask_install dropbox
  
fancy_echo "Installing Adobe Creative Cloud..."
  brew_cask_install adobe-creative-cloud

fancy_echo "Installing Spotify ..."
  brew_cask_install spotify

fancy_echo "Installing Hammerspoon ..."
  brew_cask_install hammerspoon

fancy_echo "Installing ShiftIt.spoon"
  if [ ! -d $HOME/.hammerspoon/Spoons/ShiftIt.spoon ]; then
    curl https://github.com/peterklijn/hammerspoon-shiftit/raw/master/Spoons/ShiftIt.spoon.zip -o ./ShiftIt.spoon.zip -L
    unzip ShiftIt.spoon.zip
    open ShiftIt.spoon
    rm ShiftIt.spoon.zip
    cat <<EOT>> ~/.hammerspoon/init.lua
hs.loadSpoon("ShiftIt")
spoon.ShiftIt:bindHotkeys({})
EOT
  else
    less_fancy_echo "... skiping, already ShiftIt.spoon already installed."
  fi


fancy_echo "Creating coding workspace"
  if [ ! -e $HOME/workspace ]; then
    mkdir -p $HOME/workspace
  fi

git_clone() {
  if [ ! -d $2 ]; then
    git clone $1 $2
  else
    less_fancy_echo "... skip cloning $1, already cloned"
  fi

  true
}

fancy_echo "Installing Oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

fancy_echo "Cloning laptop repo"
  git_clone git@github.com:parisyee/laptop.git ~/workspace/laptop

fancy_echo "Cloning dotfiles repo and running rcup"
  git_clone git@github.com:parisyee/dotfiles.git ~/workspace/dotfiles
  rcup -v -d ~/workspace/dotfiles

fancy_echo "Installing Vundle ..."
  if [ ! -e $HOME/.vim/bundle/Vundle.vim ]; then
    mkdir -p $HOME/.vim/bundle/
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  fi
  vim +PluginInstall +qall
  
fancy_echo "Using Tomorrow Night theme for vim"
  if [ ! -e $HOME/.vim/colors ]; then
    mkdir -p $HOME/.vim/colors
    cp ~/.vim/bundle/vim-tomorrow-theme/colors/*.vim ~/.vim/colors/
  fi
